name: scientificpython
channels:
  - defaults
dependencies:
  - backcall=0.1.0
  - bleach=2.1.3
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - colorama=0.3.9
  - cycler=0.10.0
  - cython=0.28.2
  - decorator=4.3.0
  - entrypoints=0.2.3
  - freetype=2.8
  - html5lib=1.0.1
  - icc_rt=2017.0.4
  - icu=58.2
  - intel-openmp=2018.0.0
  - ipykernel=4.8.2
  - ipython=6.3.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - jedi=0.12.0
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libpng=1.6.34
  - libsodium=1.0.16
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mistune=0.8.3
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - msys2-conda-epoch=20160418
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.4.1
  - numpy=1.14.2
  - openssl=1.0.2o
  - pandas=0.22.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.2.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - prompt_toolkit=1.0.15
  - pygments=2.2.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - python=3.6.5
  - python-dateutil=2.7.2
  - pytz=2018.4
  - pywinpty=0.5.1
  - pyzmq=17.0.0
  - qt=5.9.5
  - qtconsole=4.3.1
  - scipy=1.0.1
  - send2trash=1.5.0
  - setuptools=39.1.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.23.1
  - terminado=0.8.1
  - testpath=0.3.1
  - tornado=5.0.2
  - traitlets=4.3.2
  - vc=14
  - vs2015_runtime=14.0.25123
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.0
  - widgetsnbextension=3.2.1
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.2.5
  - zlib=1.2.11
  - pip:
    - version-information==1.0.3

